<?php
/**
 * PYCOGROUP
 * Author: phuong.nvh
 * Testimonial Info Form
 */

class Nover_Testimonials_Block_Adminhtml_Testimonials_Feedback_Edit_Form extends Mage_Adminhtml_Block_Widget_Form{

    protected function _prepareLayout()
    {
        $return = parent::_prepareLayout(); // TODO: Change the autogenerated stub
        if (Mage::getSingleton('cms/wysiwyg_config')->isEnabled()) {
            $this->getLayout()->getBlock('head')->setCanLoadTinyMce(true);
        }
        return $return;
    }

    protected function _prepareForm()
    {
        $form = new Varien_Data_Form(
            array(
                'id' => 'edit_form',
                'action' => $this->getUrl('*/*/save', array('id' => $this->getRequest()->getParam('id'))),
                'method' => 'post',
            )
        );
        $form->setUseContainer(true);
        $this->setForm($form);

        $form->setHtmlIdPrefix('feedback_');

        $fieldset = $form->addFieldset(
            'feedbacks_form', array('legend' => Mage::helper('testimonials')->__('Feedback Information'))
        );

        $testimonials = Mage::getModel('testimonials/info')->getCollection();

        $tArr = array();

        foreach($testimonials as $t){
            $tArr[] = array(
                'value' => $t->getId(),
                'label' => $t->getTestimonialName()
                );
        }

        $fieldset->addField(
            'testimonial_id',
            'select',
            array(
                'label' => Mage::helper('testimonials')->__('Testimonial'),
                'name' => 'testimonial_id',
                'values' => $tArr,
                'required' => true,
            )
        );

        $fieldset->addField(
            'username',
            'text',
            array(
                'label' => Mage::helper('testimonials')->__('User email'),
                'name' => 'username',
                'class' => 'validate-email',
                'required' => true,
            )
        );

        $fieldset->addField('content', 'editor',
            array (
                'name' => 'content',
                'label' => Mage::helper('testimonials')->__('Content'),
                'title' => Mage::helper('testimonials')->__('Content'),
                'style' => 'width: 700px; height: 200px',
                'config' => Mage::getSingleton('cms/wysiwyg_config')->getConfig()));

        $fieldset->addField(
            'status',
            'select',
            array(
                'label' => Mage::helper('testimonials')->__('Status'),
                'name' => 'status',
                'values' => Mage::getSingleton('testimonials/feedback_status')->getFormArray(),
            )
        );

        if (Mage::getSingleton('adminhtml/session')->getFeedbackData()) {
            $form->setValues(Mage::getSingleton('adminhtml/session')->getFeedbackData());
            Mage::getSingleton('adminhtml/session')->setFeedbackData(null);
        } elseif (Mage::registry('feedback_data')) {
            $form->setValues(Mage::registry('feedback_data')->getData());
        }
        return parent::_prepareForm();
    }
}