<?php
/**
 * PYCOGROUP
 * Author: phuong.nvh
 * Testimonials Resource Model Info Collection
 */

class Nover_Testimonials_Model_Resource_Info_Collection extends Mage_Core_Model_Resource_Db_Collection_Abstract{

    public function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
        $this->_init('testimonials/info');
    }
}