<?php
/**
 * PYCOGROUP
 * Author: phuong.nvh
 * Testimonial Info Form
 */

class Nover_Testimonials_Block_Adminhtml_Testimonials_Edit_Form extends Mage_Adminhtml_Block_Widget_Form{

    protected function _prepareLayout()
    {
        $return = parent::_prepareLayout(); // TODO: Change the autogenerated stub
        if (Mage::getSingleton('cms/wysiwyg_config')->isEnabled()) {
            $this->getLayout()->getBlock('head')->setCanLoadTinyMce(true);
        }
        return $return;
    }

    protected function _prepareForm()
    {
        $form = new Varien_Data_Form(
            array(
                'id' => 'edit_form',
                'action' => $this->getUrl('*/*/save', array('id' => $this->getRequest()->getParam('id'))),
                'method' => 'post',
            )
        );
        $form->setUseContainer(true);
        $this->setForm($form);

        $form->setHtmlIdPrefix('testimonial_');

        $fieldset = $form->addFieldset(
            'testimonials_form', array('legend' => Mage::helper('testimonials')->__('Testimonial Information'))
        );

        $fieldset->addField(
            'testimonial_name',
            'text',
            array(
                'label' => Mage::helper('testimonials')->__('Testimonial Name'),
                'name' => 'testimonial_name',
                'required' => true
            )
        );

        $fieldset->addField('content', 'editor',
            array (
                'name' => 'content',
                'label' => Mage::helper('testimonials')->__('Content'),
                'title' => Mage::helper('testimonials')->__('Content'),
                'style' => 'width: 700px; height: 200px',
                'config' => Mage::getSingleton('cms/wysiwyg_config')->getConfig()));

        $fieldset->addField(
            'status',
            'select',
            array(
                'label' => Mage::helper('testimonials')->__('Status'),
                'name' => 'status',
                'values' => array(
                    array(
                        'value' => 0,
                        'label' => Mage::helper('testimonials')->__('Disabled'),
                    ),
                    array(
                        'value' => 1,
                        'label' => Mage::helper('testimonials')->__('Enabled'),
                    ),
                ),
            )
        );

        if (Mage::getSingleton('adminhtml/session')->getTestimonialData()) {
            $form->setValues(Mage::getSingleton('adminhtml/session')->getTestimonialData());
            Mage::getSingleton('adminhtml/session')->setTestimonialData(null);
        } elseif (Mage::registry('testimonial_data')) {
            $form->setValues(Mage::registry('testimonial_data')->getData());
        }
        return parent::_prepareForm();
    }
}