<?php
/**
 * PYCOGROUP
 * Author: phuong.nvh
 * Testimonials Model Info Class
 */

class Nover_Testimonials_Model_Info extends Mage_Core_Model_Abstract {

    public function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
        $this->_init('testimonials/info');
    }

    public function getEnabledTestimonials(){

        $testimonials = $this->getCollection()
            ->addFieldToFilter('status', Mage::getSingleton('testimonials/info_status')->getEnabledStatusId());

        return $testimonials;
    }
}