<?php
/**
 * PYCOGROUP
 * Author: phuong.nvh
 * Testimonials Resource Model Feedback Collection
 */

class Nover_Testimonials_Model_Resource_Feedback_Collection extends Mage_Core_Model_Resource_Db_Collection_Abstract{

    public function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
        $this->_init('testimonials/feedback');
    }
}